Algoritmo "soma de dois numeros"
// Disciplina   : [Desenvolver Algoritmos] 
// Professor   : Jefferson Vinícios da Fonseca e Silva 

Var
numero1, numero2, soma:real


Inicio
escreval("digite o primeiro numero")
leia(numero1)

escreval("digite o primero numero")
leia(numero2)

// Calcula a soma dos dois números
   soma := numero1 + numero2

// Exibe o resultado da soma
   escreval("A soma dos números é: ", soma)



Fimalgoritmo